version: "3.3"

services:
  testsmarttimetable:
    container_name: testsmarttimetable
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
            - "./data:/code/data"
    ports:
      - "9021:5000"
    environment:
            - COMPOSE_PROJECT_NAME=testsmarttimetable

